import SideBar from "./_component/sidebar/SideBar";
import "./globals.css";

export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className="relative h-full w-full">
        <main className="flex h-full flex-row">
          <SideBar />
          <div className="relative z-0 mb-10 w-full p-10 sm:absolute sm:left-[12rem] sm:w-[calc(100%-12rem)] lg:left-[15rem] lg:w-[calc(100%-15rem)]">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
